@startuml pipeline_sonic
title Pipeline Sonic
allowmixing

legend
//Ref: esp-adf/cloud_services/google_translate_device//
//Ref: esp-adf/audio_processing/pipeline_resample//
//Ref: esp-adf/audio_processing/pipeline_sonic//
//Ref: esp-adf/audio_processing/pipeline_spiffs_amr_resample//
end legend

node "SD Card" as SDCard  {
    portout "SDCard Sink | SDCard Source" as SDCardSinkSource
}

node "ESP Device" as ESPDevice  {

    json "<b><color navy>Periph Set" as periph_set {
        "<i>sdcard_handle" : "periph_sdcard",
        "<i>button_handle" : {
            "Mode <PRESS | LONG_PRESSED>" : "!is_modify_speed",
            "Rec <PRESSED>" : ["Stop Playback", "Start [Record]"],
            "Rec <RELEASE | LONG_RELEASE>" : ["Stop [Record]", "Start Playback"]
        },
        "<i>touch_periph" : "periph_touch"
    }
    
    portin "SDCard Source | SDCard Sink" as EspSDCardSinkSource

    component "Pipeline Play" as pipeline_play {

        component fatfs_reader_el [
            <b>fatfs_reader_el
            ....
            <i>fatfs_stream
            ....
            <i>.type = AUDIO_STREAM_READER
            <i>_setinfo(..., 16k, 1ch, 16bits, ...)
            <i>_set_uri(..., "/sdcard/rec.wav")
            ....
            [file_reader]
            ....
            <i><color olive>...
        ]

        component wav_decoder_el [
            <b>wav_decoder_el
            ....
            <i>wav_decoder
            ....
            ...
            ....
            [wav_decoder]
            ....
            <i><color olive>...
        ]
        
        component sonic_el [
            <b>sonic_el
            ....
            <i>sonic
            ....
            <i>.sonic_info.samplerate = 16k
            <i>.sonic_info.channel = 1ch
            <i>.sonic_info.resample_linear_interpolate = 1
            <i>._set_pitch_and_speed_info(..., SONIC_PITCH, ...) ||
            <i>._set_pitch_and_speed_info(..., ..., SONIC_SPEED)
            ....
            [sonic]
            ....
            <i><color olive>...
        ]        

        component i2s_writer_el [
            <b>i2s_writer_el
            ....
            <i>i2s_stream
            ....
            <i>.type = AUDIO_STREAM_WRITER
            <i>.i2s_config.channel_format = I2S_CHANNEL_FMT_ONLY_LEFT
            <i>_set_clk(..., 16k, 1ch, 16bits,...)
            ....
            [i2s_writer]
            ....
            <i><color olive>...
        ]
    }

    component "Pipeline Record" as pipeline_rec {

        component fatfs_writer_el [
            <b>fatfs_writer_el
            ....
            <i>fatfs_stream
            ....
            <i>.type = AUDIO_STREAM_WRITER
            <i>_setinfo(..., 16k, 1ch, 16bits, ...)
            <i>_set_uri(..., "/sdcard/rec.wav")
            ....
            [file_writer]
            ....
            <i><color olive>...
        ]
        
        component wav_encoder_el [
            <b>wav_encoder_el
            ....
            <i>wav_encoder
            ....
            <i>...
            ....
            [wav_encoder]
            ....
            <i><color olive>...
        ]

        component i2s_reader_el [
            <b>i2s_reader_el
            ....
            <i>i2s_stream
            ....
            <i>.type = AUDIO_STREAM_READER
            <i>_setinfo(..., 16k, 1ch, 16bits, ...)
            ....
            [i2s_reader]
            ....
            <i><color olive>...
        ]
    }

    component HALCodec [
        <b>audio_hal_ctrl_codec
        ....
        <i>AUDIO_HAL_CODEC_MODE_BOTH
        ....
        [codec_chip]
    ]

    portout "Analog Source | Analog Sink" as AnalogSourceSink
} 

node "Analog Audio" as AnalogAudio  {
    portin "Analog Sink | Analog Source" as AnalogSinkSource
}


SDCardSinkSource   <-- EspSDCardSinkSource  #line:red;line.dotted;text:red  : Save

EspSDCardSinkSource  <-- fatfs_writer_el    #line:red;line.dotted;text:red
fatfs_writer_el <-- wav_encoder_el          #line:red;line.bold;text:red
wav_encoder_el  <-- i2s_reader_el           #line:red;line.bold;text:red
i2s_reader_el   <-- HALCodec                #line:red;line.dotted;text:red
HALCodec        <-- AnalogSourceSink        #line:red;line.dotted;text:red

AnalogSourceSink <-- AnalogSinkSource       #line:red;line.dotted;text:red  : Mic




SDCardSinkSource --> EspSDCardSinkSource #line:black;line.dotted;text:black : Read

EspSDCardSinkSource  --> fatfs_reader_el #line:black;line.dotted;text:black
fatfs_reader_el --> wav_decoder_el       #line:black;line.bold;text:black
wav_decoder_el  --> sonic_el             #line:black;line.bold;text:black
sonic_el        --> i2s_writer_el        #line:black;line.bold;text:black
i2s_writer_el   --> HALCodec             #line:black;line.dotted;text:black
HALCodec        --> AnalogSourceSink     #line:black;line.dotted;text:black

AnalogSourceSink --> AnalogSinkSource    #line:black;line.dotted;text:black : Speaker

@enduml