@startuml pipeline_embed_flash_tone
title Pipeline Embed Flash Tone
allowmixing

legend
Note: MP3/Tone is embed in program/flash!
//Ref: esp-adf/get-started/play_mp3_control//
//Ref: esp-adf/player/pipeline_embed_flash_tone//
end legend

node "ESP Device" as ESPDevice {

    component "Play Pipeline" as PlayPipeline {
        component GEmbedTone [
            <b>g_embed_tone
            ....
            <i><color olive>_binary_alarm_mp3_start
            <i><color olive>_binary_new_message_mp3_start
        ]

        component EmbedFlashStream [
            <b>embed_flash_stream
            ....
            <i>...
            ....
            embed_flash_stream_reader
            [embed flash]
            ....
            <i>...
        ]

        component Mp3Decoder [
            <b>mp3_decoder
            ....
            ...
            ....
            mp3_decoder
            [mp3]
            ....
            <i><color olive>msg.source_type == AUDIO_ELEMENT_TYPE_ELEMENT
            <i><color olive>msg.cmd == AEL_MSG_CMD_REPORT_MUSIC_INFO
        ]

        component I2SStream [
            <b>i2s_stream
            ....
            <i>.type = AUDIO_STREAM_WRITER
            ....
            i2s_stream_writer
            [i2s]
            ....
            <i><color olive>msg.source_type == AUDIO_ELEMENT_TYPE_ELEMENT
            <i><color olive>msg.cmd == AEL_MSG_CMD_REPORT_STATUS
            <i><color olive>msg.data == AEL_STATUS_STATE_STOPPED ||
            <i><color olive>msg.data == AEL_STATUS_STATE_FINISHED
        ]
    }

    component HALCodec [
        <b>audio_hal_ctrl_codec
        ....
        <i><color red>AUDIO_HAL_CODEC_MODE_BOTH?
        ....
        [codec_chip]
    ]

    portout "Analog Source" as AnalogSource
} 

node "Analog Audio" as AnalogAudio  {
    portin "Analog Sink" as AnalogSink
}

GEmbedTone --> EmbedFlashStream #line:black;line.dotted;text:black
EmbedFlashStream --> Mp3Decoder #line:black;line.bold;text:black
Mp3Decoder --> I2SStream        #line:black;line.bold;text:black
I2SStream  --> HALCodec         #line:black;line.dotted;text:black
HALCodec   --> AnalogSource     #line:black;line.dotted;text:black

AnalogSource --> AnalogSink     #line:black;line.dotted;text:black

@enduml
