@startuml pipeline_wav_amr_sdcard
title Pipeline WAV AMR SDCard
allowmixing

legend
//Ref: esp-adf/player/pipeline_raw_http//
//Ref: esp-adf/player/pipeline_recording_to_sdcard//
//Ref: esp-adf/player/pipeline_play_sdcard_music//
//Ref: esp-adf/player/pipeline_wav_amr_sdcard//
end legend

node "SDCard" as SDCard {
    portout "SDCard Sink" as SdcardSink
}

node "ESP Device" as ESPDevice {

    json "<b><color navy>Periph Set" as periph_set {
        "<i>sdcard_handle" : "periph_sdcard"
    }

    portin "SDCard Source" as SdcardSource

    component "Pipeline WAV" as PipelineWav {

        component WavFatfsStream [
            <b>wav_fatfs_stream_writer
            ....
            <i>.type = AUDIO_STREAM_WRITER
            ....
            _set_uri("/sdcard/rec_out.wav")
            ....
            wav_fatfs_stream_writer
            [wav_file / fatfs]
            ....
            <i><color olive>...
        ]

        component WavDecoder [
            <b>wav_encoder
            ....
            <i>[wav]
            ....
            wav_encoder
            [enc]
            ....
            <i><color olive>...
        ]

        component I2SStream [
            <b>i2s_stream
            ....
            <i>.type = AUDIO_STREAM_READER
            <i>.i2s_config.sample_rate = 8000 or 16000
            <i>.multi_out_num = 1
            <i>.task_core = 1
            <i>.i2s_config.channel_format = I2S_CHANNEL_FMT_ONLY_LEFT
            ....
            _set_multi_output_ringbuf(..., _get_output_ringbuf(el_raw_reader), ...)
            ....
            i2s_stream_reader
            [i2s]
            ....
            <i><color olive>msg.source_type == AUDIO_ELEMENT_TYPE_ELEMENT
            <i><color olive>msg.cmd == AEL_MSG_CMD_REPORT_STATUS
            <i><color olive>msg.data == AEL_STATUS_STATE_STOPPED ||
            <i><color olive>msg.data == AEL_STATUS_STATE_FINISHED
        ]
    }

    component "Pipeline AMR" as PipelineAmr {

        component AmrFatfsStream [
            <b>amr_fatfs_stream_writer
            ....
            <i>.type = AUDIO_STREAM_WRITER
            <i>.task_core = 1
            ....
            _set_uri("/sdcard/rec_out.amr") || 
            _set_uri("/sdcard/rec_out.Wamr")
            ....
            amr_fatfs_stream_writer
            [amr_file / fatfs]
            ....
            <i><color olive>...
        ]

        component AmrEncoder [
            <b>amr_encoder
            ....
            <i>[Wamr | amr]
            ....
            amr_encoder
            [enc]
            ....
            <i><color olive>...
        ]

       component ElRawStream [
            <b>el_raw_reader
            ....
            <i>.type = AUDIO_STREAM_READER
            ....
            RAW_STREAM
            [amr_raw]
            ....
            <i><color olive>...
        ]
    }

    component HALCodec [
        <b>audio_hal_ctrl_codec
        ....
        <i>AUDIO_HAL_CODEC_MODE_ENCODE
        ....
        [codec_chip]
    ]

    portout "Analog Sink" as AnalogSink
} 

node "Analog Audio" as AnalogAudio  {
    portin "Analog Source" as AnalogSource
}

SdcardSink <-- SdcardSource      #line:red;line.dotted;text:red

SdcardSource  <-- WavFatfsStream #line:red;line.dotted;text:red
WavFatfsStream<-- WavDecoder     #line:red;line.bold;text:red
WavDecoder    <-- I2SStream      #line:red;line.bold;text:red
I2SStream  <-- HALCodec          #line:red;line.dotted;text:red
HALCodec   <-- AnalogSink        #line:red;line.dotted;text:red

SdcardSource  <-- AmrFatfsStream #line:red;line.dotted;text:red
AmrFatfsStream<-- AmrEncoder     #line:red;line.bold;text:red
AmrEncoder    <-- ElRawStream    #line:red;line.bold;text:red
ElRawStream   <-- I2SStream      #line:red;line.dotted;text:red

AnalogSink <-- AnalogSource     #line:red;line.dotted;text:red

@enduml
