@startuml pipeline_sdcard_mp3_control
title Pipeline SDCard MP3 Control
allowmixing

legend
//Ref: esp-adf/player/pipeline_play_sdcard_music//
//Ref [sink/list]: esp-adf/player/pipeline_a2dp_sink_stream//
//Ref [sink/list]: esp-adf/player/pipeline_sdcard_mp3_control//
end legend

node "SDCard" as SDCard {
    portout "SDCard Source" as SdcardSource
}

node "ESP Device" as ESPDevice {
    json "<b><color navy>Periph set" as periph_set {
        "<i>button_handle": "periph_key",
        "<i>touch_periph": "periph_touch",
        "<i>sdcard_handle" : "periph_sdcard",
        "<i><color navy>input_key_service" : {
            "CLICK_RELEASE":["[Play] Star, pause or resume", 
                             "[Set]  Next",
                             "[Vol+] Vol+",
                             "[Vol-] Vol-"
            ],
            "PRESS":["[long Vol+] next",
                     "[long Vol-] Previous"
            ]
        }
    }

    portin "SDCard Sink" as SdcardSink

    component "Play Pipeline" as PlayPipeline {

        component FatfsStream [
            <b>fatfs_stream
            ....
            <i>.type = AUDIO_STREAM_READER
            ....
            fatfs_stream_reader
            [file / fatfs]
            ....
            <i>...
        ]

        component Mp3Decoder [
            <b>mp3_decoder
            ....
            <i>[dec]
            ....
            mp3_decoder
            [mp3]
            ....
            <i><color olive>msg.source_type == AUDIO_ELEMENT_TYPE_ELEMENT
            <i><color olive>msg.cmd == AEL_MSG_CMD_REPORT_MUSIC_INFO
        ]

        component ResampleFilter [
            <b>rsp_filter
            ....
            <i>...
            ....
            rsp_filter
            [filter]
            ....
            <i><color olive>...
        ]

        component I2SStream [
            <b>i2s_stream
            ....
            <i>.type = AUDIO_STREAM_WRITER
            <i>.i2s_config.sample_rate = 48000
            ....
            i2s_stream_writer
            [i2s]
            ....
            <i><color olive>msg.source_type == AUDIO_ELEMENT_TYPE_ELEMENT
            <i><color olive>msg.cmd == AEL_MSG_CMD_REPORT_STATUS
            <i><color olive>msg.data == AEL_STATUS_STATE_FINISHED
        ]

        component HALCodec [
            <b>audio_hal_ctrl_codec
            ....
            <i>AUDIO_HAL_CODEC_MODE_DECODE
            ....
            [codec_chip]
        ]
    }

    portout "Analog Source" as AnalogSource
} 

node "Analog Audio" as AnalogAudio  {
    portin "Analog Sink" as AnalogSink
}

SdcardSource --> SdcardSink     #line:black;line.bold;text:black

SdcardSink --> FatfsStream      #line:black;line.bold;text:black
FatfsStream--> Mp3Decoder       #line:black;line.bold;text:black
Mp3Decoder     --> ResampleFilter   #line:black;line.bold;text:black
ResampleFilter --> I2SStream        #line:black;line.bold;text:black
I2SStream  --> HALCodec         #line:black;line.bold;text:black
HALCodec   --> AnalogSource     #line:black;line.bold;text:black

AnalogSource --> AnalogSink     #line:black;line.bold;text:black

@enduml
